[build]
  base = "dashboard"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # For Netlify root hosting, keep base "/" so assets resolve at domain root
  VITE_BASE = "/"

